language: python
services: mongodb
python:
  - "3.6"
install:
  -  pip install -r requirements.txt
  -  pip install -q coverage
  -  pip install -q python-coveralls
before_script:
  - python setup.py develop
script:
  - nosetests -v --nocapture --with-coverage
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - kmathew@lbl.gov
    on_success: change
    on_failure: always
