_fw_name: <<QADAPTER_NAME>
rocket_launch: <<RLAUNCH_CMD>>
mppwidth: <<QADAPTER_NCORES>>
walltime: <<WALLTIME>>
queue: <<QUEUENAME>>
account: <<ACCOUNTNAME>>
job_name: <<DEFAULT_JOBNAME>>
pre_rocket: |
            <<CMD 1>>
            <<CMD 2>>
            <<CMD 3>>
            <<CMD 4>>
            <<or delete the pre-rocket entirely...>>

post_rocket: null
logdir: <<LOGDIR>>